from feast import Entity, FeatureView, FileSource, ValueType, Field
from feast.types import Int64, Float32, String
from datetime import timedelta
import os

# Define the path to the parquet file generated by src/process_data.py
# Feast requires absolute paths or paths relative to the feature_store.yaml location if running `feast apply` from there
# Since we usually run from root, let's try absolute path or relative to root
# Best practice for local setup: use absolute path or resolve it
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_PATH = os.path.join(os.path.dirname(CURRENT_DIR), "data", "processed", "data_churn.parquet")

churn_source = FileSource(
    path=DATA_PATH,
    timestamp_field="event_timestamp",
)

customer = Entity(
    name="customer_id",
    value_type=ValueType.STRING,
    description="Customer ID",
)

churn_features = FeatureView(
    name="churn_features",
    entities=[customer],
    ttl=timedelta(days=1),
    schema=[
        Field(name="gender", dtype=Int64),
        Field(name="SeniorCitizen", dtype=Int64),
        Field(name="Partner", dtype=Int64),
        Field(name="Dependents", dtype=Int64),
        Field(name="tenure", dtype=Int64),
        Field(name="PhoneService", dtype=Int64),
        Field(name="MultipleLines", dtype=Int64),
        Field(name="InternetService", dtype=Int64),
        Field(name="OnlineSecurity", dtype=Int64),
        Field(name="OnlineBackup", dtype=Int64),
        Field(name="DeviceProtection", dtype=Int64),
        Field(name="TechSupport", dtype=Int64),
        Field(name="StreamingTV", dtype=Int64),
        Field(name="StreamingMovies", dtype=Int64),
        Field(name="Contract", dtype=Int64),
        Field(name="PaperlessBilling", dtype=Int64),
        Field(name="PaymentMethod", dtype=Int64),
        Field(name="MonthlyCharges", dtype=Float32),
        Field(name="TotalCharges", dtype=Float32),
    ],
    online=True,
    source=churn_source,
    tags={},
)

